services:
  discovery-service:
    image: discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - mr-lee-msa

  gateway-service:
    image: gateway-service:latest
    container_name: gateway-service
    depends_on:
      - discovery-service
    ports:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - mr-lee-msa

  stock-service:
    image: stock-service:latest
    container_name: stock-service
    depends_on:
      - discovery-service
      - gateway-service
      - redis
      - kafka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/send_box?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - mr-lee-msa

  redis:
    image: redis
    container_name: kt-redis
    ports:
      - "6380:6379"
    networks:
      - mr-lee-msa

  kafka: # 서비스 이름
    image: apache/kafka:latest
    container_name: apache-kafka
    # [볼륨 이름]:[컨테이너 내부 경로]
    volumes:
      # - kafka-data:/var/lib/kafka/data
      - kafka-data:/tmp/kafka-logs
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      # [핵심] 리스너를 내부(9092), 외부(9094), 컨트롤러(9093) 3개로 분리
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      # [핵심] 도커 내부 애들한테는 'kafka:9092'로 오라고 하고, 인텔리제이한테는 'localhost:9094'로 오라고 명함(광고)을 다르게 파줍니다.
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=L_bJ6M3_Rhi25mZ1r0t9Mw
    networks:
      - mr-lee-msa
networks:
  mr-lee-msa:
    # Specify driver options
    driver: bridge

volumes:
  kafka-data: