spring:
  application:
    name: gateway-service # ???? ??? ??
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: stock-service # ??? ??? (???? ??)
              uri: lb://STOCK-SERVICE # lb(Load Balancer)? ?? ???? ??? ???? ??
              predicates:
                - Path=/stocks/** # http://localhost:8000/stock/... ?? ?? ??? ???
#              filters:
#                - StripPrefix=1 # ???? ? ?? ???(/stocks)? ?? ??
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # ??? ?? ??
server:
  port: 8000